### ISSUE TITLE
请问一下这个插件的关键词是什么

### ISSUE THREAD

**Issue by yuyuziYYZ** [AzideCupric/nonebot-plugin-penguin#1]
想请问一下这个插件的触发是输入什么

**Comment by AzideCupric** [comment]
- 呃...这个插件还在初步的开发阶段，还没有把他接入nonebot（换言之就是还不能在nonebot2里使用）
- 如果你想试试功能的话可以尝试运行[test_workflow.py](https://github.com/AzideCupric/nonebot-plugin-penguin/blob/main/test_workflow.py)
- 最近比较忙，插件的完善计划可能要鸽亿下(

**Comment by AzideCupric** [comment]
现在能用了喵（
